### ISSUE TITLE
Telegraf seems to have a memory leak

### ISSUE THREAD

**Issue by mattk42** [deis/monitor#111] opened 2016-06-17 16:44 UTC
In my cluster running the 2.0 official release I have noticed that telegraf works its way up to 2GB of memory usage before it seemingly gets cleaned up and starts over. 

![Memory Leak](https://www.dropbox.com/s/0b6od4y16o0z4r9/Screenshot%202016-06-17%2010.18.48.png?dl=1)

**Comment by jchauncey** [comment] 2016-06-17 16:50
Are you noticing the pod restarting a lot? There was an issue in the 0.13.x version of telegraf that caused the binary to panic when sending data to influx - https://github.com/influxdata/telegraf/issues/1268

Check the pod logs and see if you see a similar erorr message.

**Comment by mattk42** [comment] 2016-06-17 17:01
Unfortunately I actually killed off the DS, I have my own monitoring stuff in place so I shut down most of the deis-monitor components this morning.

I don't believe that the container is getting restarted though, if that was the case the container ids in the chart above would have changed.

**Comment by titilambert** [comment] 2016-06-22 19:27
Hello, I think I got the same issue.
I suspect prometheus plugin. It seems it doesn't closing connection :/
Run on you apiservers: `netstat -ntp | grep 8080 | wc -l`

**Comment by jchauncey** [comment] 2016-06-22 19:46
So we have seen this happen (especially on larger clusters) so we disabled the prometheus plugin by default in the image (although the chart turns it on). This means you will lose out on k8s metrics and container metrics. I will open an issue with telegraf and see if we can get it fixed.

**Comment by jchauncey** [comment] 2016-06-22 20:03
See here - https://github.com/influxdata/telegraf/issues/1405

**Comment by titilambert** [comment] 2016-06-22 20:25
PR  influxdata/telegraf#1406 created

**Comment by jchauncey** [comment] 2016-06-24 19:54
So I have rebuilt the image to include latest master changes. It seems to have fixed the memory leak problem but Im not 100% on that. If you want to redeploy telegraf and check it out that would be awesome.

**Comment by titilambert** [comment] 2016-06-27 16:28
@jchauncey testing today or tomorrow. I let you know when I get results ;)

**Comment by titilambert** [comment] 2016-06-28 12:58
The issue is fix for me !

**Closed as completed** 2016-06-28 13:12 UTC
